print ('Welcome to the tip calculator')
total_bill=float(input('What was the total bill? $'))
tip=float(input('How much tip would you like to give? 10, 12, or 15? '))
people=int(input('How many people to split the bill? '))
pay=(total_bill/people)*(tip/100+1)
pay=format(pay, '.2f')
print ('Each person should pay: $'+ pay)